drop table varaus cascade;
drop table tyovuoro cascade;
drop type viikonpv cascade;
drop table hlokpalvelut cascade;
drop table palvelu cascade;
drop table asiakas cascade;
drop table johto cascade;
drop table henkilokunta cascade;
drop table kayttajat cascade;
